stages:
  - "Static Analysis"
  - "Tests"

linter:
  stage: "Static Analysis"
  image: "python:3.13-trixie"

  before_script:
    - pip install -r requirements.txt
    - pip install ruff
  
  script:
    - python3 -m ruff check --preview sggo tests

tests:
  stage: "Tests"
  image: "python:3.13-trixie"
  
  before_script:
    - pip install -r requirements.txt
  
  script:
    - python3 -m unittest tests
